__merge__: ../../api/comp_method.yaml

functionality:
  name: scglue
  info:
    label: Scglue
    summary: "FILL IN: A one sentence summary of this method."
    description: |
      FILL IN: A (multi-line) description of how this method works.
    documentation_url: https://url.to/the/documentation
    repository_url: https://github.com/organisation/repository

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
