functionality:
  name: multiome_matrix
  info:
    label: multiome_matrix
    summary: "Converts data to format needed for R methods."

  arguments:
    - name: --multiomics_rna
      type: file
      required: True
      direction: input
    - name: --multiomics_atac
      type: file
      required: true
      direction: input
    - name: --rna_matrix
      type: file
      required: true
      direction: output
    - name: --atac_matrix
      type: file
      required: true
      direction: output
    - name: --rna_gene_annot
      type: file
      required: true
      direction: output
    - name: --rna_cell_annot
      type: file
      required: true
      direction: output
    - name: --atac_peak_annot
      type: file
      required: true
      direction: output
    - name: --atac_cell_annot
      type: file
      required: true
      direction: output


  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
