__merge__: ../../api/comp_method.yaml

functionality:
  name: figr
  info:
    label: figr
    summary: "GRN inference using figr"
    description: |
      GRN inference using figr.
    documentation_url: https://buenrostrolab.github.io/FigR/articles/FigR_shareseq.html

  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: r
        packages: tidyverse

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
