# __merge__: ../../api/comp_method.yaml

functionality:
  name: pycistopic
  info:
    label: pycistopic
    summary: "Cis-regulatory topic modeling using pycisTopic"
    description: |
      Cis-regulatory topic modeling using pycisTopic.
    documentation_url: https://pycistopic.readthedocs.io/en/latest/
  arguments:
    - name: --multiomics_atac
      type: file
      must_exist: true
      example: resources/grn-benchmark/multiomics_atac.h5ad
      info:
        label: multiomics_atac
        summary: "ATAC data"
        file_type: h5ad
        columns: 
          - name: dummpy
            type: string
            required: false
      required: true
    - name: --out_dir
      type: file
      direction: output
      create_parent: true
      default: 'output/pycistopic'
    - name: --qc
      type: boolean_true
      description: Whether to perform quality control
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: apassemi/scenicplus:latest
    setup:
      - type: docker
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
  - type: native
  - type: nextflow
    directives:
      label: [midtime,himem,hicpu]
