functionality:
  name: normalization
  info:
    label: normalization
    summary: "Normalize pseudobulked data"


  arguments:

    - name: --perturbation_data
      type: file 
      required: true
      

  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ sctk==0.2.2]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
