functionality:
  name: batch_correction_seurat
  info:
    label: batch_correction_seurat
    summary: "Correct batch effects using seurat"
  
  arguments:
    - name: --perturbation_data
      type: file 
      required: true

  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_images/r:1.1.0
    setup:
      - type: r
        bioc: []
        packages: []

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
